apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: my-project
      source:
        repoURL: https://github.com/gargap/argocd.git
        targetRevision: HEAD
        path: prod
      destination:
        server: '{{url}}'
        namespace: prod
      
      syncPolicy:
        syncOptions:
        - CreateNamespace=true