apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestboook
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
      - cluster: prl
        url: https://kubernetes.default.svc
      - cluster: prod
        url: https://kubernetes.default.svc
      
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: applicationset-resource
      source:
        repoURL: https://github.com/gargap/argocd.git
        targetRevision: main
        path: applicationset/apps/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: guestbook
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true  
