apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/instance: myapp-argo-application-dev
  name: myapp-new-dev
  namespace: guestbook
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp